version: "3.9"

services:
  db:
    image: postgres:16
    container_name: calendar_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${DB_PORT_CONTAINER}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./02-database/calendar_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-database/calendar_seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: 01-api/Dockerfile
    container_name: calendar_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_PROD}
      
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  webapp:
    build:
      context: ./03-webapp
      dockerfile: Dockerfile
    container_name: calendar_webapp
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "${WEBAPP_PORT}:80"
    restart: unless-stopped


volumes:
  postgres_data:
